# Generated by Django 3.2.3 on 2021-06-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_semester_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
