# Generated by Django 3.2.3 on 2021-06-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_student_enrolment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='Absent', max_length=30, null=True)),
                ('sem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.semester')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.student')),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subjects')),
            ],
        ),
    ]
