# Generated by Django 3.2.3 on 2021-06-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.branch'),
        ),
    ]
